BLACKLIST_TERMS = [
    ("8200", "sensitive_unit", 96, "Publicly known intelligence unit number"),
    ("9900", "sensitive_unit", 95, "Publicly known intelligence/geospatial unit number"),
    ("504", "sensitive_unit", 94, "Publicly known human intelligence unit number"),
    ('רמטכ"ל', "senior_rank", 98, "Senior command rank/title"),
    ("אלוף", "senior_rank", 95, "Senior military rank"),
    ('תא"ל', "senior_rank", 94, "Senior military rank abbreviation"),
    ("תת אלוף", "senior_rank", 94, "Senior military rank"),
    ('חמ"ל', "operations", 93, "Operations room terminology"),
    ('תצ"א', "intelligence", 92, "Aerial imagery intelligence abbreviation"),
    ("קריפטוגרפיה", "intelligence", 90, "Sensitive cryptography/security terminology"),
    ("מודיעין", "intelligence", 91, "Intelligence terminology"),
    ("מבצעים", "operations", 90, "Operational activity terminology"),
    ("פיקוד", "command", 90, "Command structure terminology"),
    ("מפקדה", "command", 88, "Command headquarters terminology"),
    ("סייבר", "intelligence", 86, "Potentially sensitive security domain"),
    ("לוחמה", "operations", 86, "Operational military activity"),
    ("כוננות", "operations", 84, "Operational readiness terminology"),
    ("חירום מבצעי", "operations", 90, "Operational emergency phrase"),
    ("נוהל קרב", "operations", 92, "Operational procedure phrase"),
    ("חדר מצב", "operations", 84, "Situation room phrase"),
    ("מבצע", "operations", 92, "Standalone operation term"),
    ("שם מבצע", "operations", 94, "Operation-name phrase"),
    ("חדר מבצעים", "operations", 94, "Operations room phrase"),
    ("חמ\"ל מבצעים", "operations", 96, "Operations war room phrase"),
    ("מבצעים חשאיים", "operations", 96, "Covert operations phrase"),
    ("סד\"כ", "force_structure", 93, "Order-of-battle acronym"),
    ("סדר כוחות", "force_structure", 93, "Order-of-battle phrase"),
    ("רע\"נ", "senior_role", 91, "Branch chief acronym"),
    ("ראש ענף", "senior_role", 91, "Branch chief role"),
    ("רמ\"ח", "senior_role", 92, "Department head acronym"),
    ("ראש מחלקה", "senior_role", 92, "Department head role"),
    ("רמ\"ט", "senior_role", 92, "Chief of staff acronym"),
    ("ראש מטה", "senior_role", 92, "Chief of staff role"),
    ("רמ\"א", "senior_role", 90, "Senior staff role acronym"),
    ("רל\"ש", "senior_role", 90, "Bureau chief acronym"),
    ("ראש לשכה", "senior_role", 90, "Bureau chief role"),
    ("קמב\"ץ", "operations_role", 92, "Operations officer acronym"),
    ("מח\"ט", "command_role", 93, "Brigade commander acronym"),
    ("מפקד חטיבה", "command_role", 93, "Brigade commander role"),
    ("מג\"ד", "command_role", 93, "Battalion commander acronym"),
    ("מפקד גדוד", "command_role", 93, "Battalion commander role"),
    ("מכלול מפקדים", "command_role", 90, "Commanders' cluster/forum phrase exposes command population"),
    ("בכיר", "senior_role", 88, "Senior-only role marker"),
    ("בכירים", "senior_role", 90, "Senior-only role marker"),
    ("בכירים בלבד", "senior_role", 92, "Senior-only access phrase"),
    ("רנ\"ג", "senior_rank", 90, "Senior NCO rank acronym"),
    ("רב נגד", "senior_rank", 90, "Senior NCO rank"),
    ("מצו\"ב", "sensitive_unit", 94, "Sensitive technology/cyber unit acronym"),
    ("לוטם", "sensitive_unit", 92, "IDF technology unit"),
    ("יחידה 3060", "sensitive_unit", 93, "Publicly known technology unit number phrase"),
    ("3060", "sensitive_unit", 90, "Publicly known technology unit number"),
    ("שייטת 13", "special_unit", 96, "Elite naval unit"),
    ("שייטת", "special_unit", 92, "Naval squadron/unit term"),
    ("סיירת מטכ\"ל", "special_unit", 96, "General Staff reconnaissance unit"),
    ("סיירת", "special_unit", 88, "Reconnaissance unit term"),
    ("שלדג", "special_unit", 95, "Elite unit"),
    ("669", "special_unit", 94, "Elite rescue unit number"),
    ("דובדבן", "special_unit", 93, "Commando unit"),
    ("מגלן", "special_unit", 93, "Commando unit"),
    ("אגוז", "special_unit", 93, "Commando unit"),
    ("יהל\"ם", "special_unit", 93, "Combat engineering special unit"),
    ("עוקץ", "special_unit", 90, "Special unit"),
    ("רוכב שמיים", "special_unit", 90, "Sky Rider unit"),
    ("קומנדו", "special_unit", 91, "Commando term"),
    ("חטיבת הקומנדו", "special_unit", 93, "Commando brigade"),
    ("גולני", "combat_brigade", 91, "Combat brigade name per user policy"),
    ("חטיבת גולני", "combat_brigade", 92, "Combat brigade phrase per user policy"),
    ("גבעתי", "combat_brigade", 91, "Combat brigade name per user policy"),
    ("חטיבת גבעתי", "combat_brigade", 92, "Combat brigade phrase per user policy"),
    ("נח\"ל", "combat_brigade", 91, "Combat brigade name per user policy"),
    ("נחל", "combat_brigade", 91, "Combat brigade no-quotes form per user policy"),
    ("חטיבת הנח\"ל", "combat_brigade", 92, "Combat brigade phrase per user policy"),
    ("כפיר", "combat_brigade", 91, "Combat brigade name per user policy"),
    ("חטיבת כפיר", "combat_brigade", 92, "Combat brigade phrase per user policy"),
    ("צנחנים", "combat_brigade", 91, "Combat brigade name per user policy"),
    ("חטיבת הצנחנים", "combat_brigade", 92, "Combat brigade phrase per user policy"),
    ("מספן", "naval_structure", 91, "Navy organizational structure"),
    ("להק", "airforce_structure", 91, "Air force wing/group term"),
    ("פלגה", "naval_structure", 90, "Naval/company structure term"),
    ("פלגת", "naval_structure", 90, "Construct form of naval/company structure term"),
    ("מפח\"י", "command_structure", 92, "Command structure acronym"),
    ("מפקדת", "command_structure", 90, "Headquarters construct form"),
    ("חטיבת המבצעים", "operations", 95, "Operations brigade/division phrase"),
    ("הקריה", "sensitive_location", 93, "MoD/IDF HQ area"),
    ("מחנה רבין", "sensitive_location", 93, "IDF/MoD HQ camp"),
    ("גלילות", "sensitive_location", 91, "Sensitive location/base area"),
    ("נבטים", "sensitive_location", 91, "Airbase location"),
    ("חצרים", "sensitive_location", 91, "Airbase location"),
    ("פלמחים", "sensitive_location", 91, "Airbase/base location"),
    ("רמת דוד", "sensitive_location", 91, "Airbase location"),
    ("בצת", "sensitive_location", 88, "Sensitive location"),
    ("הבור", "operations_infrastructure", 93, "Command bunker phrase"),
    ("מתקן כליאה", "sensitive_location", 88, "Detention facility phrase"),
    ("בסיס 512", "sensitive_location", 92, "Sensitive base number phrase"),
    ("512", "sensitive_location", 86, "Sensitive base number when isolated"),
    ("הצפנה", "intelligence", 91, "Encryption term"),
    ("צופן", "intelligence", 91, "Cipher/code term"),
    ("סייבר התקפי", "cyber", 94, "Offensive cyber phrase"),
    ("פענוח", "intelligence", 90, "Decoding/interpretation term"),
    ("תצלום אוויר", "intelligence", 91, "Aerial photograph phrase"),
    ("אמל\"ח מסווג", "classified_assets", 95, "Classified weapons/equipment phrase"),
    ("אמל\"ח", "classified_assets", 90, "Weapons/equipment acronym"),
    ("צוללת", "strategic_asset", 92, "Submarine"),
    ("צוללות", "strategic_asset", 92, "Submarines"),
    ("סטי\"ל", "strategic_asset", 91, "Missile ship acronym"),
    ("סטיל", "strategic_asset", 91, "Missile ship no-quotes form"),
    ("דבור", "naval_asset", 88, "Naval patrol boat type"),
    ("דבורה", "naval_asset", 88, "Naval patrol boat type"),
    ("מטוס אדיר", "strategic_asset", 91, "F-35 aircraft Hebrew name"),
    ("טנק מרכבה", "strategic_asset", 90, "Merkava tank phrase"),
    ("בונקר תחמושת", "strategic_asset", 92, "Ammunition bunker phrase"),
    ("מרכז טילים", "strategic_asset", 92, "Missile center phrase"),
]

PUBLIC_SOURCE_BLACKLIST_TERMS = [
    ("צה\"ל", "idf_identity", 92, "Israel Defense Forces name/acronym", "idf_public:https://www.idf.il/"),
    ("מטכ\"ל", "command_structure", 94, "General Staff acronym", "idf_public:https://www.idf.il/"),
    ("רא\"ל", "senior_rank", 96, "Chief-of-staff rank abbreviation", "public_acronym:https://hadshon.education.gov.il/lexicons/acronyms-and-abbreviations/"),
    ("רב אלוף", "senior_rank", 96, "Chief-of-staff rank", "public_rank:https://www.psychometry.co.il/idf/ranks.php"),
    ("אל\"מ", "senior_rank", 93, "Colonel rank abbreviation", "public_acronym:https://hadshon.education.gov.il/lexicons/acronyms-and-abbreviations/"),
    ("אלוף משנה", "senior_rank", 93, "Colonel rank", "public_rank:https://www.psychometry.co.il/idf/ranks.php"),
    ("סא\"ל", "senior_rank", 91, "Lieutenant colonel rank abbreviation", "public_rank:https://www.psychometry.co.il/idf/ranks.php"),
    ("סגן אלוף", "senior_rank", 91, "Lieutenant colonel rank", "public_rank:https://www.psychometry.co.il/idf/ranks.php"),
    ("רס\"ן", "officer_rank", 90, "Major rank abbreviation", "public_rank:https://www.psychometry.co.il/idf/ranks.php"),
    ("רב סרן", "officer_rank", 90, "Major rank", "public_rank:https://www.psychometry.co.il/idf/ranks.php"),
    ("סרן", "officer_rank", 88, "Captain rank", "public_rank:https://www.psychometry.co.il/idf/ranks.php"),
    ("סג\"מ", "officer_rank", 86, "Second lieutenant rank abbreviation", "public_rank:https://www.psychometry.co.il/idf/ranks.php"),
    ("סגן משנה", "officer_rank", 86, "Second lieutenant rank", "public_rank:https://www.psychometry.co.il/idf/ranks.php"),
    ("קמ\"א", "officer_rank", 86, "Professional academic officer rank abbreviation", "public_rank:https://commons.wikimedia.org/wiki/File:IDF_kama.svg"),
    ("אמ\"ן", "intelligence", 96, "IDF Intelligence Directorate acronym", "public_acronym:https://hadshon.education.gov.il/lexicons/acronyms-and-abbreviations/"),
    ("אגף המודיעין", "intelligence", 96, "IDF Intelligence Directorate", "idf_public:https://www.idf.il/"),
    ("אגף המבצעים", "operations", 95, "IDF Operations Directorate", "idf_public:https://www.idf.il/"),
    ("אמ\"ץ", "operations", 94, "Operations Directorate acronym", "wiktionary_public:https://he.wiktionary.org/wiki/%D7%90%D7%92%22%D7%9D"),
    ("אג\"ם", "operations", 93, "Operations/general-staff branch acronym", "wiktionary_public:https://he.wiktionary.org/wiki/%D7%90%D7%92%22%D7%9D"),
    ("אכ\"א", "manpower_command", 90, "IDF Manpower Directorate acronym", "idf_public:https://www.idf.il/"),
    ("אט\"ל", "logistics_command", 90, "IDF Technology and Logistics Directorate acronym", "idf_public:https://www.idf.il/"),
    ("אגף התקשוב", "cyber_command", 92, "IDF C4I/Cyber directorate", "idf_public:https://www.idf.il/"),
    ("אגף התקשוב וההגנה בסב\"ר", "cyber_command", 94, "IDF C4I and Cyber Defense Directorate", "idf_public:https://www.idf.il/"),
    ("סב\"ר", "cyber_command", 90, "Cyber acronym used by IDF public pages", "idf_public:https://www.idf.il/"),
    ("פיקוד הצפון", "regional_command", 94, "IDF Northern Command", "idf_public:https://www.idf.il/"),
    ("פיקוד הדרום", "regional_command", 94, "IDF Southern Command", "idf_public:https://www.idf.il/"),
    ("פיקוד המרכז", "regional_command", 94, "IDF Central Command", "idf_public:https://www.idf.il/"),
    ("פיקוד העורף", "regional_command", 92, "IDF Home Front Command", "idf_public:https://www.idf.il/"),
    ("זרוע היבשה", "military_branch", 92, "IDF ground arm", "idf_public:https://www.idf.il/"),
    ("זרוע הים", "military_branch", 92, "IDF naval arm", "idf_public:https://www.idf.il/"),
    ("חיל האוויר", "military_branch", 93, "Israeli Air Force", "idf_public:https://www.idf.il/"),
    ("חיל הים", "military_branch", 92, "Israeli Navy", "idf_public:https://www.idf.il/"),
    ("חיל הקשר", "military_branch", 88, "Signal Corps", "idf_public:https://www.idf.il/"),
    ("כוחות מיוחדים", "operations", 92, "Special forces phrase", "idf_public:https://www.idf.il/"),
    ("תגבור כוחות", "operations", 90, "Force reinforcement phrase", "idf_public:https://www.idf.il/"),
    ("גיוס מילואים", "operations", 90, "Reserve mobilization phrase", "idf_public:https://www.idf.il/"),
    ("הערכת מצב", "operations", 88, "Situation assessment phrase", "idf_public:https://www.idf.il/"),
    ("שליטה ובקרה", "operations", 88, "Command and control phrase", "idf_public:https://www.idf.il/"),
    ("בור", "operations", 88, "Command bunker/operations center term in IDF context", "idf_public:https://www.idf.il/"),
    ("מפא\"ת", "mod_defense_rnd", 94, "MoD R&D directorate acronym", "mod_public:https://www.mod.gov.il/אגפים/מפאת"),
    ("מינהל פיתוח אמצעי לחימה ותשתית טכנולוגית", "mod_defense_rnd", 94, "MoD MAFAT full name", "mod_public:https://www.mod.gov.il/אגפים/מפאת"),
    ("מנה\"ר", "mod_procurement", 91, "MoD procurement directorate acronym", "mod_public:https://www.mod.gov.il/"),
    ("מינהל ההרכשה והייצור", "mod_procurement", 91, "MoD procurement and production directorate", "mod_public:https://www.mod.gov.il/"),
    ("סיבט", "mod_export", 90, "MoD international defense cooperation directorate", "mod_public:https://mod.gov.il/en/departments/sibat-international-defense-cooperation"),
    ("אפ\"י", "mod_export_control", 90, "MoD defense export control agency acronym", "mod_public:https://exportctrl.mod.gov.il/about/"),
    ("אגף הפיקוח על היצוא הביטחוני", "mod_export_control", 90, "MoD defense export control agency", "mod_public:https://exportctrl.mod.gov.il/about/"),
    ("רח\"ל", "national_emergency", 88, "National Emergency Authority acronym", "mod_public:https://www.mod.gov.il/"),
    ("רשות החירום הלאומית", "national_emergency", 88, "National Emergency Authority", "mod_public:https://www.mod.gov.il/"),
    ("מלמ\"ב", "defense_security", 92, "Defense establishment security director acronym", "mod_public:https://www.mod.gov.il/"),
    ("משהב\"ט", "mod_identity", 88, "Ministry of Defense acronym", "mod_public:https://www.mod.gov.il/"),
]

GREYLIST_TERMS = [
    ("יחידה", "organization", 70, "Context-sensitive organizational term"),
    ("חטיבה", "organization", 72, "Context-sensitive formation or department"),
    ("גדוד", "organization", 76, "Military formation term"),
    ("בסיס", "location", 74, "Context-sensitive base/facility term"),
    ("מתקן", "location", 68, "Context-sensitive facility term"),
    ("מחלקה", "organization", 62, "Civilian or military department"),
    ("מדור", "organization", 66, "Civilian or military section"),
    ("תרגיל", "operations", 65, "Exercise/drill term"),
    ("פרויקט", "project", 62, "Context-sensitive project term"),
    ("אגף", "organization", 63, "Context-sensitive branch term"),
    ("ענף", "organization", 63, "Context-sensitive branch term"),
    ("לשכה", "office", 60, "Administrative office; risky near ranks"),
    ("צפון", "location", 60, "Regional term; risky near operations terms"),
    ("דרום", "location", 60, "Regional term; risky near operations terms"),
    ("מרכז", "location", 58, "Regional/center term; context-sensitive"),
    ("מצב", "operations", 58, "Benign alone, risky in situation-room phrase"),
    ("חייל", "military_personnel", 64, "Military personnel term; context-sensitive"),
    ("מילואים", "military_personnel", 66, "Reserve service term; context-sensitive"),
    ("משק", "military_role", 62, "NCO abbreviation after quote normalization; context-sensitive"),
    ("קצין", "military_role", 68, "Officer role; context-sensitive outside official rank phrases"),
]

WHITELIST_TERMS = [
    ("מרפאה", "civilian_admin", 8, "Civilian medical clinic"),
    ("חדר כושר", "civilian_admin", 10, "Civilian fitness room"),
    ("מספרה", "civilian_admin", 8, "Civilian haircut service"),
    ("בדיקת דם", "civilian_admin", 8, "Civilian medical service"),
    ("אפסנאות", "civilian_admin", 20, "Administrative logistics service"),
    ("ספרייה", "civilian_admin", 8, "Library"),
    ("קבלה", "civilian_admin", 10, "Reception"),
    ("תור", "civilian_admin", 5, "Appointment"),
    ("שירות", "civilian_admin", 8, "Service"),
    ("תחזוקה", "civilian_admin", 12, "Maintenance"),
    ("ניקיון", "civilian_admin", 8, "Cleaning"),
    ("חניה", "civilian_admin", 8, "Parking"),
    ("משרד", "civilian_admin", 12, "Office"),
    ("יומן", "civilian_admin", 8, "Calendar"),
    ("הזמנה", "civilian_admin", 8, "Booking"),
    ("ציוד משרדי", "civilian_admin", 14, "Office supplies"),
    ("מועדון", "welfare", 8, "Welfare club"),
    ("שק\"ם", "welfare", 8, "Canteen/shop acronym"),
    ("כוורת", "welfare", 8, "Welfare shop"),
    ("בריכה", "welfare", 8, "Pool"),
    ("בית כנסת", "religion", 8, "Synagogue"),
    ("שיעור תורה", "religion", 8, "Religious lesson"),
    ("כיתה", "routine", 8, "Classroom"),
    ("אולם", "routine", 8, "Hall"),
    ("הרצאה", "routine", 8, "Lecture"),
    ("פריסה", "welfare", 8, "Refreshments"),
    ("שתייה", "welfare", 8, "Drinks"),
    ("אימון גופני", "welfare", 8, "Physical training"),
    ("חובש", "medical", 12, "Medic service"),
    ("רופא", "medical", 8, "Doctor"),
    ("רופא משפחה", "medical", 8, "Family doctor"),
    ("שיניים", "medical", 8, "Dental service"),
    ("מרפאת שיניים", "medical", 8, "Dental clinic"),
    ("חיסון", "medical", 8, "Vaccination"),
    ("פיזיותרפיה", "medical", 8, "Physiotherapy"),
    ("בית מרקחת", "medical", 8, "Pharmacy"),
    ("אופטיקה", "medical", 8, "Optics"),
    ("ר\"ם 2", "medical", 10, "Routine medical administration"),
    ("סיפוח", "medical_admin", 12, "Administrative attachment"),
    ("מרפ\"א", "medical", 10, "Medical center acronym"),
    ("ביקור רופא", "medical", 8, "Doctor visit"),
    ("שלישות", "hr_admin", 12, "HR administration"),
    ("ת\"ש", "hr_admin", 8, "Conditions of service acronym"),
    ("תנאי שירות", "hr_admin", 8, "Conditions of service"),
    ("מש\"קית תש", "hr_admin", 8, "Welfare/conditions of service role"),
    ("משרד קישור", "hr_admin", 8, "Liaison office"),
    ("טופס טיולים", "hr_admin", 8, "Clearance form"),
    ("ייעוץ כלכלי", "hr_admin", 8, "Financial counseling"),
    ("ייעוץ פרישה", "hr_admin", 8, "Retirement counseling"),
    ("בקו\"ם", "hr_admin", 12, "Induction center admin term"),
    ("נשקייה", "logistics", 18, "Armory as generic service without inventory detail"),
    ("מפקד", "generic_office_label", 12, "Generic commander label allowed when no rank/unit context appears"),
    ("מפקדים", "generic_office_label", 12, "Generic commanders label allowed when no rank/unit context appears"),
    ("משרד מפקד", "generic_office_label", 8, "Generic commander office label per user policy"),
    ("משרד מפקד משותף", "generic_office_label", 8, "Generic shared commander office label per user policy"),
    ("סודי", "approved_resource_label", 8, "Approved workstation/network label from production examples"),
    ("סודית", "approved_resource_label", 8, "Approved workstation/network label from production examples"),
    ("סודי ביותר", "approved_resource_label", 8, "Approved workstation/network label from production examples"),
    ("מבצעי", "approved_resource_label", 12, "Approved resource/network adjective when used as infrastructure label"),
    ("מבצעית", "approved_resource_label", 12, "Approved resource/network adjective when used as infrastructure label"),
    ("תחקיר", "approved_admin_service", 12, "Approved administrative/security-clearance service label"),
    ("תחקיר בטחוני", "approved_admin_service", 12, "Approved administrative/security-clearance service label"),
    ("צריפין", "known_unclassified_location", 8, "Known unclassified location per user policy"),
    ("שיזפון", "known_unclassified_location", 8, "Known unclassified location per user policy"),
    ("תל השומר", "known_unclassified_location", 8, "Known unclassified location per user policy"),
    ("מתפרה", "logistics", 8, "Tailoring service"),
    ("בוחן רכב", "logistics", 8, "Vehicle inspector"),
    ("מוסך", "logistics", 8, "Garage"),
    ("מוסך יחידתי", "logistics", 8, "Unit garage as generic service"),
    ("ציוד א", "logistics", 8, "Generic equipment category"),
    ("ציוד ב", "logistics", 8, "Generic equipment category"),
    ("חלפי רכב", "logistics", 8, "Vehicle parts"),
    ("טיפול תקופתי", "logistics", 8, "Periodic maintenance"),
    ("מבחן", "routine", 8, "Test"),
    ("הסמכה", "routine", 8, "Certification"),
    ("יום ד", "routine", 8, "Routine day-off/admin term"),
    ("גימלים", "medical", 8, "Sick leave"),
    ("ש\"ג", "routine", 12, "Gate guard term, routine"),
    ("מש\"ק", "routine", 12, "Generic NCO role, no context"),
    ("חפ\"ש", "routine", 12, "Generic enlisted soldier term"),
    ("קב\"ן", "medical", 8, "Mental health officer appointment"),
    ("רגילה", "routine", 8, "Leave"),
    ("מיוחדת", "routine", 8, "Special leave"),
]

PROBLEMATIC_COMBINATIONS = [
    ("לשכת אלוף", "High", 97, "Senior rank office exposes command hierarchy"),
    ('חמ"ל צפון', "High", 96, "Operations room plus region exposes operational structure"),
    ("מדור מבצעים", "High", 94, "Section plus operations exposes operational organization"),
    ("פרויקט מודיעין", "High", 93, "Project plus intelligence creates sensitive context"),
    ("בסיס 8200", "High", 98, "Facility plus sensitive unit number"),
    ("חדר מצב", "Medium", 82, "Situation-room phrase has operational semantics"),
    ("יחידת מבצעים", "High", 94, "Unit plus operations exposes operational structure"),
    ("מפקדת פיקוד", "High", 95, "Headquarters plus command exposes hierarchy"),
    ("תחקיר מבצעי", "High", 90, "Debrief plus operational context"),
    ("תרגיל חטיבה", "Medium", 84, "Exercise plus formation indicates activity"),
    ("אגף מודיעין", "High", 94, "Branch plus intelligence exposes organization"),
    ("ענף סייבר", "High", 91, "Branch plus cyber indicates sensitive capability"),
    ("מחלקת קריפטוגרפיה", "High", 93, "Department plus cryptography indicates sensitive capability"),
    ("לשכת רמטכ\"ל", "High", 98, "Chief-of-staff office exposes senior hierarchy"),
    ("לשכת רא\"ל", "High", 97, "Senior rank office exposes hierarchy"),
    ("לשכת תא\"ל", "High", 95, "Senior rank office exposes hierarchy"),
    ("לשכת אל\"ם", "High", 94, "Senior rank office exposes hierarchy"),
    ("לשכת רע\"נ", "High", 92, "Command role office exposes structure"),
    ("לשכת רמ\"ח", "High", 93, "Department-head office exposes structure"),
    ("חדר מבצעים", "High", 94, "Operations-room phrase exposes operational function"),
    ("שם מבצע", "High", 94, "Operation-name phrase indicates operational activity"),
    ("בסיס 512", "High", 92, "Base number phrase from security guide"),
    ("מרכז טילים", "High", 92, "Missile center phrase"),
    ("חדר בכירים", "High", 92, "Senior-only room exposes hierarchy"),
    ("חדר בכירים בלבד", "High", 94, "Senior-only reservation room exposes hierarchy"),
]

COMBINATION_ANCHORS = [
    ("לשכה", ["אלוף", 'תא"ל', 'רמטכ"ל', "רא\"ל", "אל\"מ", "סא\"ל", "רס\"ן", "מפקד"], "High", 94, "Administrative office plus senior role/rank exposes hierarchy"),
    ("בסיס", ["8200", "9900", "504", "3060", "512", "מודיעין", "סייבר", "פיקוד", "נבטים", "חצרים", "פלמחים"], "High", 95, "Facility plus sensitive unit/domain exposes location or organization"),
    ("פרויקט", ["מודיעין", "סייבר", "קריפטוגרפיה", "מבצעים"], "High", 92, "Project plus sensitive domain exposes capability or activity"),
    ("מדור", ["מבצעים", "מודיעין", "סייבר", "קריפטוגרפיה"], "High", 91, "Section plus sensitive domain exposes organizational structure"),
    ("מחלקה", ["מבצעים", "מודיעין", "סייבר", "קריפטוגרפיה"], "High", 90, "Department plus sensitive domain exposes organizational structure"),
    ("יחידה", ["מבצעים", "מודיעין", "סייבר", "מיוחדת"], "High", 92, "Unit plus sensitive domain exposes organization"),
    ("חמ\"ל", ["צפון", "דרום", "מרכז", "פיקוד", "מבצעים"], "High", 94, "Operations room plus region/command exposes activity"),
    ("חדר", ["מצב", "מבצעים", "פיקוד"], "Medium", 82, "Room plus operational context indicates sensitive function"),
    ("תרגיל", ["חטיבה", "גדוד", "פיקוד", "מבצעים"], "Medium", 82, "Exercise plus formation/command exposes activity"),
    ("תחקיר", ["מבצעי", "מבצעים", "מודיעין"], "High", 90, "Debrief plus operational or intelligence context is sensitive"),
    ("מפקדת", ["פיקוד הצפון", "פיקוד הדרום", "פיקוד המרכז", "פיקוד העורף", "חיל האוויר"], "High", 95, "Headquarters plus command/branch exposes command structure"),
    ("בור", ["פיקוד", "חיל האוויר", "מבצעים", "צפון"], "High", 92, "Command bunker plus command/branch exposes operations infrastructure"),
    ("מרכז", ["מודיעין", "סייבר", "מבצעים", "שליטה ובקרה"], "High", 90, "Center plus sensitive function exposes operational capability"),
    ("יחידת", ["מו\"פ", "סייבר", "מודיעין", "קשרי חוץ"], "High", 90, "Unit construct plus sensitive function exposes organization"),
    ("חדר", ["מבצעים", "מלחמה", "פיקוד", "שליטה ובקרה"], "High", 92, "Room plus operations/command exposes sensitive function"),
    ("מחסן", ["אמל\"ח", "תחמושת", "נשק"], "High", 92, "Storage plus weapons/equipment exposes asset concentration"),
    ("בונקר", ["תחמושת", "אמל\"ח"], "High", 92, "Bunker plus ammunition/equipment exposes infrastructure"),
    ("מספן", ["מודיעין", "מבצעים", "ים"], "High", 91, "Navy staff structure plus function exposes organization"),
    ("להק", ["מודיעין", "מבצעים", "אוויר"], "High", 91, "Air-force structure plus function exposes organization"),
]
